// <auto-generated />
using System;
using AppInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppInfrastructure.Migrations
{
    [DbContext(typeof(CostDBContext))]
    partial class CostDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDomain.Models.MaterialCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CostPerMeter")
                        .HasColumnType("float");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Meters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MaterialCosts");
                });

            modelBuilder.Entity("AppDomain.Models.Measurements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ArmCircumference")
                        .HasColumnType("float");

                    b.Property<double>("ArmHole")
                        .HasColumnType("float");

                    b.Property<double>("BackChest")
                        .HasColumnType("float");

                    b.Property<double>("BackFigure")
                        .HasColumnType("float");

                    b.Property<double>("Bust")
                        .HasColumnType("float");

                    b.Property<double>("CalfCircumference")
                        .HasColumnType("float");

                    b.Property<double>("Crotch")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FrontChest")
                        .HasColumnType("float");

                    b.Property<double>("FrontFigure")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("LowerBust")
                        .HasColumnType("float");

                    b.Property<double>("LowerHips")
                        .HasColumnType("float");

                    b.Property<double>("NeckDip")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDeadline")
                        .HasColumnType("datetime2");

                    b.Property<double>("Shoulder")
                        .HasColumnType("float");

                    b.Property<double>("SleeveLength")
                        .HasColumnType("float");

                    b.Property<double>("Thigh")
                        .HasColumnType("float");

                    b.Property<double>("UpperBust")
                        .HasColumnType("float");

                    b.Property<double>("UpperHips")
                        .HasColumnType("float");

                    b.Property<double>("Waistline")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("AppDomain.Models.OrderSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GrandToaCost")
                        .HasColumnType("float");

                    b.Property<double>("LaborCost")
                        .HasColumnType("float");

                    b.Property<double>("MaterialTotal")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalLaborCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OrderSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
