// <auto-generated />
using System;
using AppInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppInfrastructure.Migrations.SewingDb
{
    [DbContext(typeof(SewingDbContext))]
    [Migration("20260513070328_AddStatusToMeasurement")]
    partial class AddStatusToMeasurement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDomain.Models.Measurements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ArmCircumference")
                        .HasColumnType("float");

                    b.Property<double>("ArmHole")
                        .HasColumnType("float");

                    b.Property<double>("BackChest")
                        .HasColumnType("float");

                    b.Property<double>("BackFigure")
                        .HasColumnType("float");

                    b.Property<double>("Bust")
                        .HasColumnType("float");

                    b.Property<double>("CalfCircumference")
                        .HasColumnType("float");

                    b.Property<double>("Crotch")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FrontChest")
                        .HasColumnType("float");

                    b.Property<double>("FrontFigure")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("LowerBust")
                        .HasColumnType("float");

                    b.Property<double>("LowerHips")
                        .HasColumnType("float");

                    b.Property<double>("NeckDip")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDeadline")
                        .HasColumnType("datetime2");

                    b.Property<double>("Shoulder")
                        .HasColumnType("float");

                    b.Property<double>("SleeveLength")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Thigh")
                        .HasColumnType("float");

                    b.Property<double>("UpperBust")
                        .HasColumnType("float");

                    b.Property<double>("UpperHips")
                        .HasColumnType("float");

                    b.Property<double>("Waistline")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
